# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.57.2"

default_platform :ios

platform :ios do
    before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
#     cocoapods
#	 cocoapods(use_bundle_exec: false)

    end

    desc "Runs all the tests"
    lane :test do
        scan
    end

    desc "Create Screenshots"
    lane :screenshot do
        # SimulatorStatusMagic enabling
        ENV["SIMULATOR_STATUS_MAGIC_OVERRIDES"] = "enable"

        snapshot(
            ios_version: "11.0.1",
            devices: [
                "iPhone 5s",
#                "iPhone 6",
#                "iPhone 6 Plus",
#                "iPhone 6s",
#                "iPhone 6s Plus",
#                "iPhone 7",
#                "iPhone 7 Plus",
#                "iPhone SE",
                "iPhone 8",
                "iPhone 8 Plus",
                "iPhone X" ,
#                "iPad Air",
#                "iPad (5th generation)",
                "iPad Pro (9.7-inch)",
                "iPad Pro (12.9-inch)",
#                "iPad Pro (12.9-inch) (2nd generation)",
                "iPad Pro (10.5-inch)"
            ],
	    number_of_retries: 3
        )
    end


    desc "Generate required icon sizes and iconset"
    lane :icon do
        appicon(
        	appicon_image_file: 'Icon.png',
                appicon_devices: [:ipad, :iphone, :ios_marketing],
                appicon_path: 'SwissGrid/Assets.xcassets' # output path
        )
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :beta do
        # match(type: "appstore") # more information: https://codesigning.guide
        gym(scheme: "SwissGrid") # Build your app - more options available
        pilot

        # sh "your_script.sh"
        # You can also use other beta testing services here (run `fastlane actions`)
    end

    desc "Deploy a new version to the App Store"
    lane :release do
        # match(type: "appstore")
        # snapshot
        gym(scheme: "SwissGrid") # Build your app - more options available
        deliver
        # frameit
    end

    desc "Deploy a new version to the App Store without Screenshots and Metadata"
    lane :releaseFast do
        # match(type: "appstore")
        # snapshot
        gym(scheme: "SwissGrid") # Build your app - more options available
        deliver(
            force: true,
            skip_screenshots: true,
            skip_metadata: true,
        )
        # frameit
    end

    # You can define as many lanes as you want

    after_all do |lane|
        # This block is called, only if the executed lane was successful

        # slack(
        #     message: "Successfully deployed new App Update."
        # )
    end

    error do |lane, exception|
        # slack(
        #     message: exception.message,
        #     success: false
        # )
    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
