# Uncomment the lines below you want to change by removing the # in the beginning

# debug weird problems
#clean true
#erase_simulator true
#localize_simulator true
output_simulator_logs true

languages([
  "en-US",
  "de-DE",
  "fr-FR",
])

# The name of the scheme which contains the UI Tests
scheme "SwissGridUIScreenshots"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# Clear all previously generated screenshots before creating new ones
#clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
